version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - api
    networks:
      - app-network
    restart: always

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    environment:
      REDIS_URI: redis://default:password@redis:6379
    volumes:
      - redis_volume_data:/var/lib/redis/data
    ports:
      - 6379:6379
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    container_name: api
    image: shuvo83qn/somos-ai-voice-replication:${IMAGE_TAG}
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network
    command: node -r dotenv/config dist/index.js
    volumes:
      - ./uploads:/app/uploads
      - ./.env:/app/.env
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://127.0.0.1:5005/api/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    restart: unless-stopped

volumes:
  redis_volume_data:

networks:
  app-network:
    driver: bridge